services:
  ollama_service:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve &
       sleep 10 &&
       ollama pull gemma2:2b-instruct-q8_0 &&
       tail -f /dev/null"
    restart: unless-stopped

  rag_service:
    build:
      context: .
      dockerfile: Dockerfile.rag
    image: rag_system:latest
    volumes:
      - chroma_data:/app/data/chroma
      - model_data:/root/.cache/huggingface
    ports:
      - "8000:8000"
    environment:
      - CHROMA_DB_PATH=/app/data/chroma
      - HF_HOME=/root/.cache/huggingface
    restart: unless-stopped

volumes:
  ollama_data:
  chroma_data:
  model_data: