version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api-service
    ports:
      - "8003:8003"
    networks:
      - app-network

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: ui-service
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
