services:
  chatbot:
    build:
      context: ./ui+api
      dockerfile: Dockerfile
    container_name: api-service
    ports:
      - "9003:9003"
      - "9501:8501"
    environment:
      - LLM_IP=localhost

  ollama_service:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "ollama serve &      
       sleep 10 &&
       ollama pull gemma2:2b-instruct-q8_0 &&
       ollama pull gemma2:9b&&
       tail -f /dev/null"
    restart: unless-stopped

  rag_service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile.rag
    image: rag_system:latest
    container_name: ml-service
    volumes:
      - chroma_data:/app/data/chroma
      - model_data:/root/.cache/huggingface
    ports:
      - "8000:8000"
    environment:
      - CHROMA_DB_PATH=/app/data/chroma
      - HF_HOME=/root/.cache/huggingface
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data:
  chroma_data:
  model_data:

