version: '3'
services:
  rag_service:
    build:
      context: .
      dockerfile: Dockerfile.rag
    image: rag_system:latest
    volumes:
      - chroma_data:/app/data/chroma
      - model_data:/root/.cache/huggingface
    ports:
      - "8000:8000"
    environment:
      - CHROMA_DB_PATH=/app/data/chroma
      - HF_HOME=/root/.cache/huggingface
    restart: unless-stopped

  ollama_service:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    command: ["ollama", "run", "gemma:2b"]
    restart: unless-stopped

volumes:
  chroma_data:
    driver: local
  model_data:
    driver: local
  ollama_data:
    driver: local
